//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS3DumpChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PS3DumpChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using this software you understand that the author (Swizzy) is in no way responsible for ANY damage caused to your console...
        ///
        ///You also acknowledge that you understand that this tool is not a 100% validation of your dumps, it&apos;s only meant to make it easier to check wether or not it&apos;s worth looking closer at or not...
        ///
        ///Did you read these terms/conditions?.
        /// </summary>
        internal static string AcceptTermsMessage {
            get {
                return ResourceManager.GetString("AcceptTermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using this software you understand that the author (Swizzy) is in no way responsible for ANY damage caused to your console...
        ///
        ///You also acknowledge that you understand that this tool is not a 100% validation of your dumps, it&apos;s only meant to make it easier to check wether or not it&apos;s worth looking closer at or not...
        ///
        ///Did you skip reading these terms/conditions?.
        /// </summary>
        internal static string AcceptTermsMessageReversed {
            get {
                return ResourceManager.GetString("AcceptTermsMessageReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you read?.
        /// </summary>
        internal static string AcceptTermsTitle {
            get {
                return ResourceManager.GetString("AcceptTermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Image?.
        /// </summary>
        internal static string autopatch {
            get {
                return ResourceManager.GetString("autopatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to patch this image?.
        /// </summary>
        internal static string autopatchmsg {
            get {
                return ResourceManager.GetString("autopatchmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong during the download, try again!.
        /// </summary>
        internal static string baddwl {
            get {
                return ResourceManager.GetString("baddwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Filesize don&apos;t match expected size from the configuration! Please doublecheck your image and configuration!.
        /// </summary>
        internal static string badsize {
            get {
                return ResourceManager.GetString("badsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished grabbing changelog....
        /// </summary>
        internal static string changelogdone {
            get {
                return ResourceManager.GetString("changelogdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR - Bad dump.
        /// </summary>
        internal static string Checks_StartCheck_ERROR___Bad_dump {
            get {
                return ResourceManager.GetString("Checks_StartCheck_ERROR___Bad_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration files|*.cfg|All Files|*.*.
        /// </summary>
        internal static string conf_filter {
            get {
                return ResourceManager.GetString("conf_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crash.log.
        /// </summary>
        internal static string CrashLogName {
            get {
                return ResourceManager.GetString("CrashLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok... You can&apos;t read can you? well then... better luck next time!.
        /// </summary>
        internal static string DisclaimerFailedMessage {
            get {
                return ResourceManager.GetString("DisclaimerFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading latest PS3 Dump Checker.
        /// </summary>
        internal static string dlingapp {
            get {
                return ResourceManager.GetString("dlingapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading latest hashlist....
        /// </summary>
        internal static string dlinghashlist {
            get {
                return ResourceManager.GetString("dlinghashlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading latest CFG.
        /// </summary>
        internal static string dlinglatestcfg {
            get {
                return ResourceManager.GetString("dlinglatestcfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading changelog....
        /// </summary>
        internal static string downloadchangelog {
            get {
                return ResourceManager.GetString("downloadchangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed....
        /// </summary>
        internal static string downloadcompleted {
            get {
                return ResourceManager.GetString("downloadcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR - Bad Size.
        /// </summary>
        internal static string error_bad_size {
            get {
                return ResourceManager.GetString("error_bad_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: No configuration loaded!.
        /// </summary>
        internal static string error_noconfig {
            get {
                return ResourceManager.GetString("error_noconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR - No config!.
        /// </summary>
        internal static string error_noconfig_title {
            get {
                return ResourceManager.GetString("error_noconfig_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashlists |*.hashlist|All Files|*.*.
        /// </summary>
        internal static string hashlist_filter {
            get {
                return ResourceManager.GetString("hashlist_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP ERROR.
        /// </summary>
        internal static string httperror {
            get {
                return ResourceManager.GetString("httperror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maj {
            get {
                object obj = ResourceManager.GetObject("maj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string N_A {
            get {
                return ResourceManager.GetString("N_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file.
        /// </summary>
        internal static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Files|*.bin|All Files|*.*.
        /// </summary>
        internal static string ofdfilter {
            get {
                return ResourceManager.GetString("ofdfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send{0}{1}{0}To Swizzy@xeupd.com!.
        /// </summary>
        internal static string PleaseSendLogTo {
            get {
                return ResourceManager.GetString("PleaseSendLogTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dump to check.
        /// </summary>
        internal static string seldump {
            get {
                return ResourceManager.GetString("seldump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select configuration file to load.
        /// </summary>
        internal static string select_conf {
            get {
                return ResourceManager.GetString("select_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve found a bug!.
        /// </summary>
        internal static string YouFoundABug {
            get {
                return ResourceManager.GetString("YouFoundABug", resourceCulture);
            }
        }
    }
}
