//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS3DumpChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PS3DumpChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By using this software you understand that the author (Swizzy) is in no way responsible for ANY damage caused to your console...
        ///
        ///You also acknowledge that you understand that this tool is not a 100% validation of your dumps, it&apos;s only meant to make it easier to check wether or not it&apos;s worth looking closer at or not...
        ///
        ///Did you read these terms/conditions?.
        /// </summary>
        internal static string AcceptTermsMessage {
            get {
                return ResourceManager.GetString("AcceptTermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By using this software you understand that the author (Swizzy) is in no way responsible for ANY damage caused to your console...
        ///
        ///You also acknowledge that you understand that this tool is not a 100% validation of your dumps, it&apos;s only meant to make it easier to check wether or not it&apos;s worth looking closer at or not...
        ///
        ///Did you skip reading these terms/conditions?.
        /// </summary>
        internal static string AcceptTermsMessageReversed {
            get {
                return ResourceManager.GetString("AcceptTermsMessageReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can you read?.
        /// </summary>
        internal static string AcceptTermsTitle {
            get {
                return ResourceManager.GetString("AcceptTermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are already using the latest cfg!.
        /// </summary>
        internal static string AlreadyUsingLatestCFG {
            get {
                return ResourceManager.GetString("AlreadyUsingLatestCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are already using the latest hashlist!.
        /// </summary>
        internal static string AlreadyUsingLatestHashlist {
            get {
                return ResourceManager.GetString("AlreadyUsingLatestHashlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Patch Image?.
        /// </summary>
        internal static string autopatch {
            get {
                return ResourceManager.GetString("autopatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to patch this image?.
        /// </summary>
        internal static string autopatchmsg {
            get {
                return ResourceManager.GetString("autopatchmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Something went wrong during the download, try again!.
        /// </summary>
        internal static string baddwl {
            get {
                return ResourceManager.GetString("baddwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ERROR: Filesize don&apos;t match expected size from the configuration! Please doublecheck your image and configuration!.
        /// </summary>
        internal static string badsize {
            get {
                return ResourceManager.GetString("badsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finished grabbing changelog....
        /// </summary>
        internal static string changelogdone {
            get {
                return ResourceManager.GetString("changelogdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ERROR - Bad dump.
        /// </summary>
        internal static string Checks_StartCheck_ERROR___Bad_dump {
            get {
                return ResourceManager.GetString("Checks_StartCheck_ERROR___Bad_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration files|*.cfg|All Files|*.*.
        /// </summary>
        internal static string conf_filter {
            get {
                return ResourceManager.GetString("conf_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à crash.log.
        /// </summary>
        internal static string CrashLogName {
            get {
                return ResourceManager.GetString("CrashLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok... You can&apos;t read can you? well then... better luck next time!.
        /// </summary>
        internal static string DisclaimerFailedMessage {
            get {
                return ResourceManager.GetString("DisclaimerFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading latest PS3 Dump Checker.
        /// </summary>
        internal static string dlingapp {
            get {
                return ResourceManager.GetString("dlingapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading latest hashlist....
        /// </summary>
        internal static string dlinghashlist {
            get {
                return ResourceManager.GetString("dlinghashlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading latest CFG.
        /// </summary>
        internal static string dlinglatestcfg {
            get {
                return ResourceManager.GetString("dlinglatestcfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading changelog....
        /// </summary>
        internal static string downloadchangelog {
            get {
                return ResourceManager.GetString("downloadchangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download completed....
        /// </summary>
        internal static string downloadcompleted {
            get {
                return ResourceManager.GetString("downloadcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ERROR.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ERROR - Bad Size.
        /// </summary>
        internal static string error_bad_size {
            get {
                return ResourceManager.GetString("error_bad_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ERROR: No configuration loaded!.
        /// </summary>
        internal static string error_noconfig {
            get {
                return ResourceManager.GetString("error_noconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ERROR - No config!.
        /// </summary>
        internal static string error_noconfig_title {
            get {
                return ResourceManager.GetString("error_noconfig_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There was an error while downloading the changelog... try again later....
        /// </summary>
        internal static string ErrorDownloadingChangelog {
            get {
                return ResourceManager.GetString("ErrorDownloadingChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There was an error while downloading the update... Try again later!.
        /// </summary>
        internal static string ErrorDownloadingUpdate {
            get {
                return ResourceManager.GetString("ErrorDownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There was an error while checking for updates... try again later!.
        /// </summary>
        internal static string ErrorWhileCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorWhileCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hashlists |*.hashlist|All Files|*.*.
        /// </summary>
        internal static string hashlist_filter {
            get {
                return ResourceManager.GetString("hashlist_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HTTP ERROR.
        /// </summary>
        internal static string httperror {
            get {
                return ResourceManager.GetString("httperror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are already running the latest version, or the online version haven&apos;t been updated properly....
        /// </summary>
        internal static string LatestVersionRunningOrNotUpdatedOnline {
            get {
                return ResourceManager.GetString("LatestVersionRunningOrNotUpdatedOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maj {
            get {
                object obj = ResourceManager.GetObject("maj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N/A.
        /// </summary>
        internal static string N_A {
            get {
                return ResourceManager.GetString("N_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No file.
        /// </summary>
        internal static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Binary Files|*.bin|All Files|*.*.
        /// </summary>
        internal static string ofdfilter {
            get {
                return ResourceManager.GetString("ofdfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Woops, online version is bad! :&apos;(.
        /// </summary>
        internal static string OnlineVersionIsBad {
            get {
                return ResourceManager.GetString("OnlineVersionIsBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ERROR: Unable to patch {0} can&apos;t find: {1}.
        /// </summary>
        internal static string PatchFailedCantFindPatchFile {
            get {
                return ResourceManager.GetString("PatchFailedCantFindPatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please send{0}{1}{0}To Swizzy@xeupd.com!.
        /// </summary>
        internal static string PleaseSendLogTo {
            get {
                return ResourceManager.GetString("PleaseSendLogTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Dump to check.
        /// </summary>
        internal static string seldump {
            get {
                return ResourceManager.GetString("seldump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select configuration file to load.
        /// </summary>
        internal static string select_conf {
            get {
                return ResourceManager.GetString("select_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use embedded patches.
        /// </summary>
        internal static string UseEmbeddedPatches {
            get {
                return ResourceManager.GetString("UseEmbeddedPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use internal patcher.
        /// </summary>
        internal static string UseInternalPatcher {
            get {
                return ResourceManager.GetString("UseInternalPatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WARNING!.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à !! WARNING !!
        ///Image has failed verification (A.K.A. it&apos;s probably BAD)! 
        ///Do you really want to patch this image?.
        /// </summary>
        internal static string warningforcepatch {
            get {
                return ResourceManager.GetString("warningforcepatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You&apos;ve found a bug!.
        /// </summary>
        internal static string YouFoundABug {
            get {
                return ResourceManager.GetString("YouFoundABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have been warned....
        /// </summary>
        internal static string YouveBeenWarned {
            get {
                return ResourceManager.GetString("YouveBeenWarned", resourceCulture);
            }
        }
    }
}
