//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS3DumpChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PS3DumpChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using this software you understand that the author (Swizzy) is in no way responsible for ANY damage caused to your console...
        ///
        ///You also acknowledge that you understand that this tool is not a 100% validation of your dumps, it&apos;s only meant to make it easier to check wether or not it&apos;s worth looking closer at or not...
        ///
        ///Did you read these terms/conditions?.
        /// </summary>
        internal static string AcceptTermsMessage {
            get {
                return ResourceManager.GetString("AcceptTermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using this software you understand that the author (Swizzy) is in no way responsible for ANY damage caused to your console...
        ///
        ///You also acknowledge that you understand that this tool is not a 100% validation of your dumps, it&apos;s only meant to make it easier to check wether or not it&apos;s worth looking closer at or not...
        ///
        ///Did you skip reading these terms/conditions?.
        /// </summary>
        internal static string AcceptTermsMessageReversed {
            get {
                return ResourceManager.GetString("AcceptTermsMessageReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you read?.
        /// </summary>
        internal static string AcceptTermsTitle {
            get {
                return ResourceManager.GetString("AcceptTermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crash.log.
        /// </summary>
        internal static string CrashLogName {
            get {
                return ResourceManager.GetString("CrashLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok... You can&apos;t read can you? well then... better luck next time!.
        /// </summary>
        internal static string DisclaimerFailedMessage {
            get {
                return ResourceManager.GetString("DisclaimerFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send{0}{1}{0}To Swizzy@xeupd.com!.
        /// </summary>
        internal static string PleaseSendLogTo {
            get {
                return ResourceManager.GetString("PleaseSendLogTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use embedded patches.
        /// </summary>
        internal static string UseEmbeddedPatches {
            get {
                return ResourceManager.GetString("UseEmbeddedPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use internal patcher.
        /// </summary>
        internal static string UseInternalPatcher {
            get {
                return ResourceManager.GetString("UseInternalPatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve found a bug!.
        /// </summary>
        internal static string YouFoundABug {
            get {
                return ResourceManager.GetString("YouFoundABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been warned....
        /// </summary>
        internal static string YouveBeenWarned {
            get {
                return ResourceManager.GetString("YouveBeenWarned", resourceCulture);
            }
        }
    }
}
